Ignore unnamed series
Summary:
Series 792260 [0] is unnamed. Until D50035628 we ignored unnamed series, but my
reading of the docs was not that this case is possible and at the time there
were no such series floating around. Hence, with this change we now crash when
seeing such a series:
  > Traceback (most recent call last):
  >   File "kernel_patches_daemon/patchwork.py", line 356, in __init__
  >     self.subject = none_throws(re.match(SUBJECT_REGEXP, data["name"])).group(
  >   File "/usr/local//lib/python3.10/re.py", line 190, in match
  >     return _compile(pattern, flags).match(string)
  > TypeError: expected string or bytes-like object
  > The above exception was the direct cause of the following exception:
  > Traceback (most recent call last):
  >   File "kernel_patches_daemon/daemon.py", line 56, in run
  >     await self.run_once()
  >   File "kernel_patches_daemon/daemon.py", line 47, in run_once
  >     await self.github_sync_worker.sync_patches()
  >   File "kernel_patches_daemon/github_sync.py", line 184, in sync_patches
  >     self.subjects = await self.pw.get_relevant_subjects()
  >   File "kernel_patches_daemon/patchwork.py", line 727, in get_relevant_subjects
  >     all_series = await asyncio.gather(*tasks)
  >   File "kernel_patches_daemon/patchwork.py", line 679, in get_series_by_id
  >     self.known_series[series_id] = Series(
  >   File "kernel_patches_daemon/patchwork.py", line 360, in __init__
  >     raise ValueError(
  > ValueError: Failed to parse subject from series name 'None'

This change reinstates the original check, causing us to ignore unnamed series.

[0] https://patchwork.kernel.org/project/netdevbpf/list/?series=792260&state=*

Reviewed By: chantra, anakryiko

Differential Revision: D50194555

fbshipit-source-id: 658dcad7dc494b280376dea76f1117805032ddf7