Fix metrics logging
Summary:
D39042987 seems to have broken the metrics logging.
```
Traceback (most recent call last):
  File "kernel/kernel_patches_daemon/oss/kernel_patches_daemon/daemon.py", line 56, in run
    await self.run_once()
  File "kernel/kernel_patches_daemon/oss/kernel_patches_daemon/daemon.py", line 50, in run_once
    self.metrics_logger(self.project, self.github_sync_worker.stats)
TypeError: export() takes 2 positional arguments but 3 were given
```

Add the now-required argument to make things work again.

Reviewed By: chantra

Differential Revision: D48363262

fbshipit-source-id: e7fdc2c05e98babe52c35ebba715c7d46db1f877